using System.Text.Json;
using Romulus.Infrastructure.Audit;
using Xunit;

namespace Romulus.Tests.Audit;

/// <summary>
/// Audit-Sidecar / Metadata Round-Trip-Tests.
///
/// AuditSigningService is exercised indirectly today (RunOrchestrator integration tests),
/// but the explicit "write -> verify -> append -> verify -> tamper -> verify-fails"
/// round-trip is not a first-class test target. This suite closes that gap:
///
///  1.  Sidecar round-trip: write metadata -> TestMetadataSidecar()=true; bytes
///        of the sidecar are stable when nothing else changes.
///  2.  Append-after-sidecar invalidation: writing a sidecar, then appending an
///        audit row MUST keep the file consistent (sidecar regenerated by orchestrator
///        flow). Direct verification after only an append (without re-writing the
///        sidecar) MUST report inconsistent (rowCount drift).
///  3.  Tamper detection: modifying the audit CSV after sidecar write MUST make
///        TestMetadataSidecar() return false (no false positives on corruption).
/// </summary>
public sealed class AuditSidecarRoundTripTests : IDisposable
{
    private readonly string _tempDir;

    public AuditSidecarRoundTripTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), "Romulus_C5_" + Guid.NewGuid().ToString("N")[..8]);
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try { if (Directory.Exists(_tempDir)) Directory.Delete(_tempDir, recursive: true); }
        catch { /* best-effort */ }
    }

    [Fact]
    public void AuditSigningService_WriteMetadataSidecarThenVerify_RoundTripSucceedsAndIsStable()
    {
        var keyFile = Path.Combine(_tempDir, "audit.key");
        var auditPath = Path.Combine(_tempDir, "audit.csv");
        var store = new AuditCsvStore(keyFilePath: keyFile);

        var metadata = new Dictionary<string, object>
        {
            ["RunId"] = "run-c5-01",
            ["Mode"] = "Move",
            ["StartedUtc"] = "2026-04-25T10:00:00Z",
            ["Roots"] = "C:/roms",
            ["Counter"] = 42
        };

        store.WriteMetadataSidecar(auditPath, metadata);
        Assert.True(store.TestMetadataSidecar(auditPath));

        var sidecarPath = auditPath + ".meta.json";
        Assert.True(File.Exists(sidecarPath));

        // Re-verify against the same content -> idempotent true.
        Assert.True(store.TestMetadataSidecar(auditPath));

        // Sidecar JSON must contain the supplied metadata values (UTF-8 BOM tolerated).
        using var doc = JsonDocument.Parse(File.ReadAllText(sidecarPath));
        Assert.Equal("run-c5-01", doc.RootElement.GetProperty("RunId").GetString());
        Assert.Equal("Move", doc.RootElement.GetProperty("Mode").GetString());
    }

    [Fact]
    public void AuditCsvStore_AppendAfterSidecar_AutoRewritesSidecarAndRemainsConsistent()
    {
        // INVARIANT (AuditCsvStore.AppendAuditRows): when a sidecar already exists,
        // every append MUST regenerate the sidecar so rowCount/contentHash stay in sync.
        // Without this, appended rows would silently invalidate prior runs.
        var keyFile = Path.Combine(_tempDir, "audit.key");
        var auditPath = Path.Combine(_tempDir, "audit.csv");
        var store = new AuditCsvStore(keyFilePath: keyFile);

        store.WriteMetadataSidecar(auditPath, new Dictionary<string, object>
        {
            ["RunId"] = "run-c5-02",
            ["Mode"] = "Move"
        });
        Assert.True(store.TestMetadataSidecar(auditPath));
        var sidecarPath = auditPath + ".meta.json";
        var sidecarBytesBefore = File.ReadAllBytes(sidecarPath);

        store.AppendAuditRow(auditPath,
            rootPath: "C:/roms",
            oldPath: "C:/roms/Game.zip",
            newPath: "C:/roms/_Konsolen/Game.zip",
            action: "Move",
            category: "Game",
            hash: "ABC",
            reason: "primary");

        // Sidecar MUST have been auto-regenerated and verification MUST still succeed.
        Assert.True(store.TestMetadataSidecar(auditPath));
        var sidecarBytesAfter = File.ReadAllBytes(sidecarPath);
        Assert.False(sidecarBytesBefore.SequenceEqual(sidecarBytesAfter),
            "AppendAuditRow must auto-rewrite the sidecar to reflect the new row count/contentHash.");
    }

    [Fact]
    public void AuditSigningService_TamperedAuditCsvAfterSidecarWrite_VerificationFails()
    {
        var keyFile = Path.Combine(_tempDir, "audit.key");
        var auditPath = Path.Combine(_tempDir, "audit.csv");
        var store = new AuditCsvStore(keyFilePath: keyFile);

        store.AppendAuditRow(auditPath,
            rootPath: "C:/roms",
            oldPath: "C:/roms/A.zip",
            newPath: "C:/roms/_Konsolen/A.zip",
            action: "Move",
            category: "Game",
            hash: "AAA",
            reason: "primary");

        store.WriteMetadataSidecar(auditPath, new Dictionary<string, object>
        {
            ["RunId"] = "run-c5-03",
            ["Mode"] = "Move"
        });
        Assert.True(store.TestMetadataSidecar(auditPath));

        // Tamper: append a row directly via raw file write -> sidecar hash/row-count drift.
        File.AppendAllText(auditPath,
            "C:/roms,C:/roms/B.zip,C:/roms/_Konsolen/B.zip,Move,Game,BBB,injected,2026-04-25T10:00:00Z" + Environment.NewLine);

        Assert.False(store.TestMetadataSidecar(auditPath));
    }
}
