function Get-RomCleanupWpfSelectionConfig {
  return [ordered]@{
    PreferMap = [ordered]@{
      chkPreferEU    = 'EU'
      chkPreferUS    = 'US'
      chkPreferWORLD = 'WORLD'
      chkPreferJP    = 'JP'
      chkPreferDE    = 'DE'
      chkPreferFR    = 'FR'
      chkPreferIT    = 'IT'
      chkPreferES    = 'ES'
      chkPreferAU    = 'AU'
      chkPreferASIA  = 'ASIA'
      chkPreferKR    = 'KR'
      chkPreferCN    = 'CN'
      chkPreferBR    = 'BR'
      chkPreferNL    = 'NL'
      chkPreferSE    = 'SE'
      chkPreferSCAN  = 'SCAN'
    }
    PreferDefaults = @('EU', 'US', 'WORLD', 'JP')
    ExtensionsMap  = [ordered]@{
      chkExtChd  = '.chd'
      chkExtIso  = '.iso'
      chkExtZip  = '.zip'
      chkExt7z   = '.7z'
      chkExtRar  = '.rar'
      chkExtCue  = '.cue'
      chkExtGdi  = '.gdi'
      chkExtImg  = '.img'
      chkExtBin  = '.bin'
      chkExtCso  = '.cso'
      chkExtPbp  = '.pbp'
      chkExtNsp  = '.nsp'
      chkExtXci  = '.xci'
      chkExtWbfs = '.wbfs'
      chkExtRvz  = '.rvz'
      chkExtNds  = '.nds'
      chkExtGba  = '.gba'
      chkExtNes  = '.nes'
    }
    ConsoleMap = [ordered]@{
      chkConsPS1    = 'PS1'
      chkConsPS2    = 'PS2'
      chkConsPS3    = 'PS3'
      chkConsPSP    = 'PSP'
      chkConsGC     = 'GC'
      chkConsWII    = 'WII'
      chkConsWIIU   = 'WIIU'
      chkConsSWITCH = 'SWITCH'
      chkConsNES    = 'NES'
      chkConsSNES   = 'SNES'
      chkConsN64    = 'N64'
      chkConsGB     = 'GB'
      chkConsGBC    = 'GBC'
      chkConsGBA    = 'GBA'
      chkConsNDS    = 'NDS'
      chkCons3DS    = '3DS'
      chkConsMD     = 'MD'
      chkConsSCD    = 'SCD'
      chkConsSAT    = 'SAT'
      chkConsDC     = 'DC'
      chkConsSMS    = 'SMS'
      chkConsGG     = 'GG'
      chkConsARCADE = 'ARCADE'
      chkConsNEOGEO = 'NEOGEO'
      chkConsNEOCD  = 'NEOCD'
      chkConsPCE    = 'PCE'
      chkConsPCECD  = 'PCECD'
      chkConsDOS    = 'DOS'
      chkCons3DO    = '3DO'
      chkConsJAG    = 'JAG'
    }
  }
}
